
set_target_properties(${APP_NAME} PROPERTIES
        XCODE_ATTRIBUTE_GCC_PREPROCESSOR_DEFINITIONS "WITH_NANOVG_GPU=1 HAS_AWTK_CONFIG=1 "
        XCODE_ATTRIBUTE_CLANG_ENABLE_OBJC_WEAK YES
        XCODE_ATTRIBUTE_GCC_WARN_64_TO_32_BIT_CONVERSION NO
        XCODE_ATTRIBUTE_GCC_WARN_ABOUT_RETURN_TYPE YES_ERROR
        XCODE_ATTRIBUTE_GCC_WARN_UNDECLARED_SELECTOR YES
        XCODE_ATTRIBUTE_GCC_WARN_UNINITIALIZED_AUTOS YES_AGGRESSIVE
        XCODE_ATTRIBUTE_GCC_WARN_UNUSED_FUNCTION YES
        XCODE_ATTRIBUTE_GCC_WARN_UNUSED_VARIABLE YES
        XCODE_ATTRIBUTE_CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING YES
        XCODE_ATTRIBUTE_CLANG_WARN_BOOL_CONVERSION NO
        XCODE_ATTRIBUTE_CLANG_WARN_COMMA YES
        XCODE_ATTRIBUTE_CLANG_WARN_CONSTANT_CONVERSION NO
        XCODE_ATTRIBUTE_CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS YES
        XCODE_ATTRIBUTE_CLANG_WARN_DIRECT_OBJC_ISA_USAGE YES_ERROR
        XCODE_ATTRIBUTE_CLANG_WARN_DOCUMENTATION_COMMENTS NO
        XCODE_ATTRIBUTE_CLANG_WARN_EMPTY_BODY YES
        XCODE_ATTRIBUTE_CLANG_WARN_ENUM_CONVERSION YES
        XCODE_ATTRIBUTE_CLANG_WARN_INFINITE_RECURSION YES
        XCODE_ATTRIBUTE_CLANG_WARN_INT_CONVERSION NO
        XCODE_ATTRIBUTE_CLANG_WARN_NON_LITERAL_NULL_CONVERSION NO
        XCODE_ATTRIBUTE_CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF YES
        XCODE_ATTRIBUTE_CLANG_WARN_OBJC_LITERAL_CONVERSION YES
        XCODE_ATTRIBUTE_CLANG_WARN_OBJC_ROOT_CLASS YES_ERROR
        XCODE_ATTRIBUTE_CLANG_WARN_RANGE_LOOP_ANALYSIS YES
        XCODE_ATTRIBUTE_CLANG_WARN_STRICT_PROTOTYPES YES
        XCODE_ATTRIBUTE_CLANG_WARN_SUSPICIOUS_MOVE YES 
        XCODE_ATTRIBUTE_CLANG_WARN_UNGUARDED_AVAILABILITY YES_AGGRESSIVE
        XCODE_ATTRIBUTE_CLANG_WARN_UNREACHABLE_CODE YES 
        XCODE_ATTRIBUTE_CLANG_WARN__DUPLICATE_METHOD_MATCH YES 
)
