
set_target_properties(${APP_NAME} PROPERTIES
        XCODE_ATTRIBUTE_GCC_PREPROCESSOR_DEFINITIONS "WITH_NANOVG_GPU=1 HAS_AWTK_CONFIG=1 WITH_DATA_READER_WRITER=1 EXTRA_DEFINES"
        XCODE_ATTRIBUTE_CLANG_ENABLE_OBJC_WEAK YES
        XCODE_ATTRIBUTE_GCC_WARN_64_TO_32_BIT_CONVERSION NO
        XCODE_ATTRIBUTE_GCC_WARN_ABOUT_RETURN_TYPE YES_ERROR
        XCODE_ATTRIBUTE_GCC_WARN_UNDECLARED_SELECTOR NO
        XCODE_ATTRIBUTE_GCC_WARN_UNINITIALIZED_AUTOS NO 
        XCODE_ATTRIBUTE_GCC_WARN_UNUSED_FUNCTION NO
        XCODE_ATTRIBUTE_GCC_WARN_UNUSED_VARIABLE NO
				XCODE_ATTRIBUTE_GCC_WARN_UNUSED_LABEL NO
				XCODE_ATTRIBUTE_GCC_WARN_UNUSED_PARAMETER NO
				XCODE_ATTRIBUTE_GCC_WARN_UNUSED_VALUE NO
        XCODE_ATTRIBUTE_CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING NO
        XCODE_ATTRIBUTE_CLANG_WARN_BOOL_CONVERSION NO
        XCODE_ATTRIBUTE_CLANG_WARN_COMMA NO
        XCODE_ATTRIBUTE_CLANG_WARN_CONSTANT_CONVERSION NO
        XCODE_ATTRIBUTE_CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS NO
        XCODE_ATTRIBUTE_CLANG_WARN_DIRECT_OBJC_ISA_USAGE YES_ERROR
        XCODE_ATTRIBUTE_CLANG_WARN_DOCUMENTATION_COMMENTS NO
        XCODE_ATTRIBUTE_CLANG_WARN_EMPTY_BODY NO
        XCODE_ATTRIBUTE_CLANG_WARN_ENUM_CONVERSION NO
        XCODE_ATTRIBUTE_CLANG_WARN_INFINITE_RECURSION NO
        XCODE_ATTRIBUTE_CLANG_WARN_INT_CONVERSION NO
        XCODE_ATTRIBUTE_CLANG_WARN_NON_LITERAL_NULL_CONVERSION NO
        XCODE_ATTRIBUTE_CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF NO
        XCODE_ATTRIBUTE_CLANG_WARN_OBJC_LITERAL_CONVERSION NO
        XCODE_ATTRIBUTE_CLANG_WARN_OBJC_ROOT_CLASS YES_ERROR
        XCODE_ATTRIBUTE_CLANG_WARN_RANGE_LOOP_ANALYSIS NO
        XCODE_ATTRIBUTE_CLANG_WARN_STRICT_PROTOTYPES NO
        XCODE_ATTRIBUTE_CLANG_WARN_SUSPICIOUS_MOVE NO 
        XCODE_ATTRIBUTE_CLANG_WARN_UNGUARDED_AVAILABILITY NO
        XCODE_ATTRIBUTE_CLANG_WARN_UNREACHABLE_CODE NO 
        XCODE_ATTRIBUTE_CLANG_WARN__DUPLICATE_METHOD_MATCH NO 
)
